# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]

custom: ["https://explorer.cardano.org/en/address?address=addr1q9crzwlzrtakg9r69f048n5c3csg0q6me7rc8fkkwjqe4ehghc9desu36s9pdnyn5kc8m6qq7tf4lugshsuxq87npjdq600555", "https://etherscan.io/address/0x53f1368589a4e1ebb72f0a0c61fd8bc06e776e2f"]
